// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8FeYNSdLMoD_GylXe34B7dshBo0ywnj8',
    appId: '1:528972588206:web:98ac3185946f2daa1fb93f',
    messagingSenderId: '528972588206',
    projectId: 'pushnotification-d358b',
    authDomain: 'pushnotification-d358b.firebaseapp.com',
    storageBucket: 'pushnotification-d358b.firebasestorage.app',
    measurementId: 'G-YKLMDYF0V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtR-JnuJcTW5wsWbL5r6ylkqwZlQZwlUk',
    appId: '1:528972588206:android:f84478ab566bf3da1fb93f',
    messagingSenderId: '528972588206',
    projectId: 'pushnotification-d358b',
    storageBucket: 'pushnotification-d358b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDqB67001_EuNHF6o4FfoySta3S1ZLmQI',
    appId: '1:528972588206:ios:8e91fa7c82e4de9b1fb93f',
    messagingSenderId: '528972588206',
    projectId: 'pushnotification-d358b',
    storageBucket: 'pushnotification-d358b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCloudMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDqB67001_EuNHF6o4FfoySta3S1ZLmQI',
    appId: '1:528972588206:ios:8e91fa7c82e4de9b1fb93f',
    messagingSenderId: '528972588206',
    projectId: 'pushnotification-d358b',
    storageBucket: 'pushnotification-d358b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCloudMessaging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8FeYNSdLMoD_GylXe34B7dshBo0ywnj8',
    appId: '1:528972588206:web:43e2950331b87c981fb93f',
    messagingSenderId: '528972588206',
    projectId: 'pushnotification-d358b',
    authDomain: 'pushnotification-d358b.firebaseapp.com',
    storageBucket: 'pushnotification-d358b.firebasestorage.app',
    measurementId: 'G-DQ98FLCBQX',
  );
}
